pub const MESSAGE_OK: &str = "ok";
pub const MESSAGE_NOT_FOUND: &str = "not found";
pub const MESSAGE_CANT_VERIFY: &str = "can't verify";
pub const MESSAGE_FAIL_INSERT: &str = "fail to inserting user";
pub const MESSAGE_FAIL_UPDATE: &str = "fail to updating user";
pub const MESSAGE_FAIL_SEND_MAIL: &str = "fail to sending mail";
pub const MESSAGE_DUPLICATED_EMAIL: &str = "duplicated email";
pub const ERROR_INVALID_URI: &str = "Invalid uri";
pub const ERROR_INTERNEAL_ERROR: &str = "internel error";
